name: Build firmware

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build ${{ matrix.board_name }}
    runs-on: ubuntu-latest
    container:
      image: espressif/idf@sha256:cbc2e2ec2afee95f1cfa14acfa3bb6cc69a51816537fe0234f4429e71a881066 # v5.5.1
    strategy:
      fail-fast: false
      matrix:
        include:
          - board_name: ESP32
            target: esp32
            sdkconfig_defaults: sdkconfig.defaults.esp32.debug
          - board_name: ESP32-S3
            target: esp32s3
            sdkconfig_defaults: sdkconfig.defaults.esp32s3.debug
          - board_name: ESP32-S2 Mini
            target: esp32s2
            sdkconfig_defaults: sdkconfig.defaults.esp32s2.debug

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          submodules: recursive

      - name: Clone external components
        run: |
          git clone --filter=blob:none --recursive https://github.com/espressif/idf-extra-components.git ../idf-extra-components
          git -C ../idf-extra-components checkout 78a16155b4842a120f46a3e57d8c8898f15c2f71 # 2026-03-20

          git clone --filter=blob:none --recursive https://github.com/Strefa35/esp-drivers.git ../esp-drivers
          git -C ../esp-drivers checkout 214b9818ee29e28b7c67b426638753f5480054b5 # 2026-01-26

      - name: Build firmware for ${{ matrix.target }}
        shell: bash
        run: |
          set -euo pipefail
          . /opt/esp/idf/export.sh
          rm -rf build sdkconfig
          cp "${{ matrix.sdkconfig_defaults }}" sdkconfig.defaults
          idf.py set-target "${{ matrix.target }}"
          idf.py build

      - name: Upload build artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: esp-platform-${{ matrix.target }}
          path: |
            build/*.bin
            build/*.elf
            build/*.map
            build/bootloader/*.bin
            build/partition_table/*.bin
            build/flasher_args.json
            sdkconfig
          if-no-files-found: error
